program: train.py
method: grid
parameters:
  # constant parameters
  batch_size:
    value: 32
  epochs:
    value: 20

  # grid parameters
  model_name:
    values:
      - "squeezenet1_1"             # 1.2M
      - "mobilenet_v2"              # 3.5M
      - "nvidia_efficientnet_b4"    # 19.3M
      - "resnet50"                  # 25.0M
      - "resnext50_32x4d"           # 25.0M
      - "swin_v2_t"                 # 28M
      - "maxvit_t"                  # 31M
      - "vit_b_16"                  # 86.4M
      - "resnext101_32x8d"          # 88.8M
  learning_rate:
    values:
      - 3e-4
      - 1e-3
      - 3e-3
  
# command line arguments
command:
  - ${env}
  - python
  - ${program}
  - "--data_dir=./data/train_images"
  - "--save_dir=./output_models"